name: test-python
on: 
  push: 
    branches:
      - '*'
    paths-ignore:
      - 'code-cov/*'
      - 'CWL/*'
jobs:
  check-docker-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          token: ${{secrets.GH_TOKEN}}
      - name: say hello
        run: echo "Hello"
      - name: check python version 
        run: python3 --version
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: check python version again
        run: python3 --version
      - name: check docker version
        run: docker --version
      - name: run tests
        run: make test
      - name: push code-cov
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make push-cov
